# 测试配置文件
# @author <a href="">程序员远行</a>
# @from <">公众号：所谓远行Misnearch</a>
server:
  port: 8101
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuanmian_db
    username: root
    password: 12345
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      timeout: 10s
      password: 123456
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456